### PR TITLE
BUGFIX: Fix reloading of Monocle Preview

### PR DESCRIPTION
**Pull request by bwaidelich**
Fixes: #98

### CODE REVIEW

**Comment by bwaidelich** [comment]
The smallest fix ever.
Probably there are more efficient ways to solve this, but it fixes the reloading issue for me

**Comment by kdambekalns** [comment]
I can confirm it fixes the issue.

**Comment by kdambekalns** [comment]
But the linter is unhappy:

```
60:10  error  '_' is assigned a value but never used        no-unused-vars
60:10  error  '_' is never reassigned. Use 'const' instead  prefer-const
```

**Comment by mficzel** [comment]
Linter should be happy now, will merge once green and release 6.0.1

**Pull request merged**
