### PR TITLE
FEATURE: Add `useCases` for styleguide prototypes

### PR DESCRIPTION
**Pull request by mficzel**
The `useCases` section of the `@styleguide` annotation allows to configure scenarios the component shall be previewed in.
If a useCase defines `props` or `container` those are will override the styleguide settings for this component. The `title`
is optional and will fallback to the key the useCase is defined in.

```
prototype(Vendor.Site:Example.Component) < prototype(Neos.Fusion:Component) {

    @styleguide {
        title = "Example"

        container = Vendor.Site:Example.Container
        props {
            title = 'Hello world!'
        }

        useCases {
            case1 {
                title = "Use case with varying props"
                props {
                    title = Hello special world!'
                }
            }
            case2 {
                title = "Use case with another container"
                container = Vendor.Site:Example.AnotherContainer
            }
        }
```

!!! PropSets are now deprecated and cannot not be mixed with UseCases. Monocle will not show the PropSet selector for components that have useCases and the API endpoint will ignore propSets once a useCase is selected. The PropSet Feature will be removed in one of the next major versions once if causes extra effort to the monocle maintenance !!!

Resolves: #133 
Resolves: #112 (this is an unrelated bug)

### CODE REVIEW

**Comment by mficzel** [comment]
@grebaldi what do you think about this .. it is built upon the container feature and adds useCases that allow to completely override props and containers.

The backend side is prepared so far. I disabled the 'useCases' in the api the styleguide uses for now to avoid js errors. If you like this change i would go ahead and try to add a useCase Selector analog to the PropSet selector to the ui for now. 

As i would not recommend to mix useCases and propSets this should be goof enough for now.

**Review by grebaldi — COMMENTED** [review]
I like the concept. :) 

And I would actually say it would be best to deprecate propSets in favor of this.

In the meantime, using both concepts simultaneously should throw an Exception imho.

**Comment by mficzel** [comment]
@grebaldi I agree to deprecate propSets but would define that useCases simply take precedence. Throwing Errors would require to adjust the ui which is additional work for us.

**Comment by mficzel** [comment]
@grebaldi tried to extend and am sure i am almost there ... however typeScript is complaining in weird ways now. I could use some help to understand those errors.

**Pull request merged**
